config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pipelines, param: :name, only: [:index] do
    resources :work_orders, only: %i[index show] do
      resources :lab_events
    end
    get 'reception', to: 'reception#index'
    post 'reception/upload', to: 'reception#upload'
    scope module: 'gridion' do
      resources :sequencing_runs
    end
  end

  resources :print_jobs, only: %i[create]

  match 'test_exception_notifier', controller: 'application',
                                   action: 'test_exception_notifier', via: :get

  # think about root
  root 'pipelines#index'
end

app/models/gridion/sequencing_run.rb
# frozen_string_literal: true

module Gridion
  # Gridion SequencingRun
  class SequencingRun < ApplicationRecord
    has_many :flowcells, inverse_of: :sequencing_run,
                         foreign_key: :gridion_sequencing_run_id
    has_many :work_orders, through: :flowcells

    enum state: %i[pending completed user_terminated instrument_crashed restart]

    validates_presence_of :instrument_name

    accepts_nested_attributes_for :flowcells,
                                  reject_if: proc { |attributes| attributes['work_order_id'].blank? },
                                  allow_destroy: true

    scope :by_date, (-> { order(created_at: :desc) })

    with_options if: :flowcells_present? do
      validates_with MaximumFlowcellValidator
      validates_with WorkOrderLibraryValidator
    end

    before_destroy :destroy_flowcells_and_update_work_orders

    def experiment_name
      super || id
    end

    def work_orders_include_unsaved
      work_orders.empty? ? flowcells.collect(&:work_order) : work_orders
    end

    def flowcells_present?
      flowcells.present?
    end

    # returns result of sequencing_run
    # returns nil if sequencing_run is pending, 'completed' if completed, 'failed' otherwise
    def result
      return if pending?
      return state if completed?
      'failed'
    end

    # TODO: create(destroy) lab events from one place

    # before destroying sequencing run, it removes work_orders from sequencing state
    # (by removing sequencing lab_events) then destroys flowcells
    def destroy_flowcells_and_update_work_orders
      work_orders.each { |work_order| work_order.aliquot.destroy_sequencing_events }
      flowcells.destroy_all
    end
  end
end

app/controllers/gridion/sequencing_runs_controller.rb
# frozen_string_literal: true

module Gridion
  # SequencingRuns Controller
  class SequencingRunsController < ApplicationController
    attr_reader :sequencing_runs, :sequencing_run

    before_action :set_sequencing_run, only: %i[show]
    before_action :sequencing_runs, only: %i[index]

    def index; end

    def new
      @sequencing_run = SequencingRunForm.new
    end

    def create
      @sequencing_run = SequencingRunForm.new
      if sequencing_run.submit(sequencing_run_params)
        redirect_to pipeline_sequencing_run_path(pipeline, sequencing_run),
                    notice: 'Sequencing run successfully created'
      else
        render :new
      end
    end

    def edit
      @sequencing_run = SequencingRunForm.new(current_resource)
    end

    def update
      @sequencing_run = SequencingRunForm.new(current_resource)
      if sequencing_run.submit(sequencing_run_params)
        redirect_to pipeline_sequencing_run_path(pipeline, sequencing_run),
                    notice: 'Sequencing run successfully updated'
      else
        render :edit
      end
    end

    def show; end

    def destroy
      current_resource.destroy
      redirect_to pipeline_sequencing_runs_path(pipeline),
                  notice: 'Sequencing run successfully deleted'
    end

    protected

    def sequencing_runs
      @sequencing_runs = SequencingRun.by_date
    end

    def set_sequencing_run
      @sequencing_run ||= current_resource
    end

    def current_resource
      @current_resource = SequencingRun.includes(:flowcells).find(params[:id]) if params[:id].present?
    end

    def sequencing_run_params
      params.require(:gridion_sequencing_run).permit(:experiment_name, :instrument_name, :state,
                                                     flowcells_attributes:
                                                     %i[id flowcell_id position work_order_id _destroy])
    end

    helper_method :sequencing_runs, :sequencing_run
  end
end

app/views/gridion/sequencing_runs/_form.html.erb
<%= form_for [pipeline, sequencing_run], url: (sequencing_run.new_record? ? pipeline_sequencing_runs_path : pipeline_sequencing_run_path(pipeline, sequencing_run)) do |f| %>
  <fieldset class="container">
    <legend>
      Sequencing Run
    </legend>
    <%= render "error_messages", target: sequencing_run %>
    <% if sequencing_run.experiment_name.present? %>
      <div class="form-group" >
        <%= f.label :experiment_name %>
        <%= f.text_field :experiment_name, { class: 'form-control' } %>
      </div>
    <% end %>
    <div class="form-group" >
      <%= f.label :instrument_name %>
      <%= f.text_field :instrument_name, { class: 'form-control' } %>
    </div>
    <div class="form-group" >
      <%= f.label :state %>
      <%= f.select :state, Gridion::SequencingRun.states.keys, {}, { class: 'form-control' } %>
    </div>
     <div class="row">
      <div class="col-md-12">
        <table class="table">
        <thead>
          <th>Position</th>
          <th>Flowcell ID</th>
          <th>Sample</th>
        </thead>
        <tbody>
          <% sequencing_run.flowcells_by_position.each do |flowcell| %>
            <%= f.fields_for :flowcells, flowcell do |fields_for_flowcell| %>
               <tr id="flowcell_<%= flowcell.position %>">
              <td><%= flowcell.position %></td>
              <td>
                <div class="form-group" ><%= fields_for_flowcell.text_field :flowcell_id %></div>
              </td>
              <td>
                <div class="form-group" ><%= fields_for_flowcell.select(:work_order_id, options_from_collection_for_select(sequencing_run.available_work_orders, 'id', 'unique_name', flowcell.work_order_id), {include_blank: 'Select sample...'}, class: 'select2' ) %></div>
              </td>
              <td>
                <div class="form-group" >
                  <%= fields_for_flowcell.check_box :_destroy %>
                  <%= fields_for_flowcell.label :delete %>
                </div>
              </td>
            </div>
            <%= fields_for_flowcell.hidden_field(:position, value: flowcell.position) %>
            <% end %>
          <% end %>
        </tbody>
        </table>
      </div>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-primary pull-right' %>
    </div>
  </fieldset>
<% end %>

app/views/gridion/sequencing_runs/edit.html.erb
<%= render 'form' %>

app/views/gridion/sequencing_runs/index.html.erb
<div class="title row">
  <div class="col">
    <h2>
    Sequencing Runs <%= link_to new_pipeline_sequencing_run_path(pipeline), { class: 'btn btn-primary btn-large pull-right', role: 'button' } do %>
        <%= fa_icon "plus" %> New Sequencing Run
      <% end %>
    </h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <th>Experiment name</th>
        <th>Instrument name</th>
        <th>Created</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
      </thead>
    <tbody>
      <% sequencing_runs.each do |sequencing_run| %>
        <tr id="<%= dom_id(sequencing_run) %>">
          <td><%= sequencing_run.experiment_name %></td>
          <td><%= sequencing_run.instrument_name %></td>
          <td><%= sequencing_run.created_at.to_date.to_s(:default) %></td>
          <td><%= link_to 'Show', pipeline_sequencing_run_path(pipeline, sequencing_run) %></td>
          <td><%= link_to 'Edit', edit_pipeline_sequencing_run_path(pipeline, sequencing_run) %></td>
          <td><%= link_to 'Delete', pipeline_sequencing_run_path(pipeline, sequencing_run), method: :delete%>
        </tr>
      <% end %>
    </tbody>
    </table>
  </div>
</div>

app/views/gridion/sequencing_runs/new.html.erb
<%= render 'form' %>

app/views/gridion/sequencing_runs/show.html.erb
<section>
  <h2>Sequencing Run</h2>
  <ul>
    <li>
      <strong>experiment name: </strong><%= sequencing_run.experiment_name %>
    </li>
    <li>
      <strong>instrument name: </strong><%= sequencing_run.instrument_name %>
    </li>
  </ul>
  <h3>Flowcells</h3>
  <div class="row">
    <div class="col-md-12">
      <table class="table">
        <thead>
          <th>Position</th>
          <th>Flowcell ID</th>
          <th>Sample</th>
        </thead>
        <tbody>
          <% sequencing_run.flowcells.includes(work_order: :aliquot).order(:position).each do |flowcell| %>
            <tr>
              <td><%= flowcell.position %></td>
              <td><%= flowcell.flowcell_id %></td>
              <td><%= flowcell.work_order.unique_name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>