config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pipelines, param: :name, only: [:index] do
    resources :work_orders, only: %i[index show] do
      resources :lab_events
    end
    get 'reception', to: 'reception#index'
    post 'reception/upload', to: 'reception#upload'
    scope module: 'gridion' do
      resources :sequencing_runs
    end
  end

  resources :print_jobs, only: %i[create]

  match 'test_exception_notifier', controller: 'application',
                                   action: 'test_exception_notifier', via: :get

  # think about root
  root 'pipelines#index'
end

app/models/sqsc/api/work_order.rb
# frozen_string_literal: true

module Sqsc
  module Api
    # creates WorkOrder objects based on json received from sqsc api
    class WorkOrder < Base
      has_many :samples
      has_one :source_receptacle

      def self.for_reception
        includes(:samples, :source_receptacle).where(state: 'pending').all
      end

      def self.find_by_ids(ids)
        includes(:samples, :source_receptacle).where(id: ids.join(',')).all
      end

      def self.find_by_id(id)
        where(id: id).all.try(:first)
      end

      def update_state_to(state)
        update_attributes(state: state)
      end

      def name
        source_receptacle.name
      end

      def sample_uuid
        samples.first.uuid
      end

      def not_ready_for_upload
        name.nil? || id.nil? || sample_uuid.nil?
      end
    end
  end
end

app/models/work_order.rb
# frozen_string_literal: true

# WorkOrder
class WorkOrder < ApplicationRecord
  belongs_to :aliquot

  has_many :work_order_requirements

  attr_readonly :sequencescape_id, :study_uuid, :sample_uuid

  validates_presence_of :sequencescape_id, :study_uuid, :sample_uuid

  accepts_nested_attributes_for :aliquot, :work_order_requirements

  delegate_missing_to :aliquot
  delegate :state, :next_state, to: :aliquot, prefix: true

  scope :by_date, (-> { order(created_at: :desc) })

  # returns an array of work_orders in particular state within pipeline
  def self.by_pipeline_and_aliquot_state(pipeline, aliquot_state = nil)
    all_work_orders_in_pipeline = work_orders_in_pipeline(pipeline)
    if aliquot_state.present?
      all_work_orders_in_pipeline.select { |work_order| work_order.aliquot_state == aliquot_state.to_s }
    else
      all_work_orders_in_pipeline
    end
  end

  # returns an array of work_orders with particular next state within pipeline
  def self.by_pipeline_and_aliquot_next_state(pipeline, aliquot_next_state = nil)
    all_work_orders_in_pipeline = work_orders_in_pipeline(pipeline)
    if aliquot_next_state.present?
      all_work_orders_in_pipeline.select { |work_order| work_order.aliquot_next_state == aliquot_next_state.to_s }
    else
      all_work_orders_in_pipeline
    end
  end

  # returns an array of all work_orders within pipeline
  def self.work_orders_in_pipeline(pipeline)
    select { |work_order| work_order.pipeline == pipeline }
  end

  def unique_name
    "#{id}:#{name}"
  end

  # this is work_order requirements
  # they are different for different pipelines
  # OpenStruct is used to be able to call a method with requirement name
  # example work_order.details.number_of_flowcells
  # TODO think about refactoring it
  def details
    @details ||= OpenStruct.new(work_order_requirements.collect(&:to_h).inject(:merge!))
  end

  def went_through_step(step_name)
    aliquot.lab_event?(step_name)
  end
end

app/controllers/work_orders_controller.rb
# frozen_string_literal: true

# WorkOrders Controller
class WorkOrdersController < ApplicationController
  attr_reader :work_orders, :work_order

  before_action :set_work_order, only: %i[show]

  def index
    @work_orders = WorkOrder.by_date
                            .includes(aliquot: { lab_events: { process_step: :pipeline } })
                            .by_pipeline_and_aliquot_next_state(pipeline, params[:process_step_name])
  end

  def show; end

  protected

  def set_work_order
    @work_order ||= current_resource
  end

  def current_resource
    @current_resource = WorkOrder.find(params[:id]) if params[:id].present?
  end

  helper_method :work_orders, :work_order
end

app/views/work_orders/_aliquot.html.erb
  <%= form.fields_for :aliquot, work_order.aliquot do |aliquot| %>
    <div class="form-group" >
      <%= aliquot.label :concentration %>
      <%= aliquot.text_field :concentration, { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= aliquot.label :fragment_size %>
      <%= aliquot.text_field :fragment_size, { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= aliquot.label :qc_state, 'QC state' %>

       <div class="row">
        <div class="col-md-11">
          <%= aliquot.select :qc_state, Aliquot.qc_states.keys, { class: 'form-control' } %>
        </div>
      </div>
    </div>
  <% end %>

app/views/work_orders/_form.html.erb
<%= form_for work_order do |f| %>
  <fieldset class="container">
    <legend>
      Work Order
    </legend>
    <%= render "error_messages", target: work_order %>
    <div><%= work_order.name %></div>
    <div><%= work_order.state %></div>
    <%= render work_order.template, form: f %>
    <div class="form-group">
      <%= f.submit class: 'btn btn-primary pull-right' %>
    </div>
  </fieldset>
<% end %>

app/views/work_orders/_library.html.erb
<%= form.fields_for :library, Library.new do |library| %>
  <div class="form-group" >
    <%= library.label :volume %>
    <%= library.text_field :volume, { class: 'form-control' } %>
  </div>
  <div class="form-group" >
    <%= library.label :kit_number %>
    <%= library.text_field :kit_number, { class: 'form-control' } %>
  </div>
  <div class="form-group" >
    <%= library.label :ligase_batch_number %>
    <%= library.text_field :ligase_batch_number, { class: 'form-control' } %>
  </div>
<% end %>

app/views/work_orders/_print.html.erb
<%= label_tag :printer, 'Printer', class: 'h6' %>
<%= select_tag(:printer_name, options_for_select(printers_names)) %>
<%= submit_tag "Print labels", class: "btn btn-secondary btn-sm" , disabled: printers_names.empty?, data: { disable_with: "Please wait..." }%>

app/views/work_orders/edit.html.erb
<%= render 'form', work_order: @work_order %>

app/views/work_orders/index.html.erb
<div class="title row">
  <div class="col-md-12">
    <h2>Work Orders</h2>
  </div>
</div>
<%= render 'work_orders' %>

app/views/work_orders/show.html.erb
<section>
  <h2>Work Order - <%= work_order.name %></h2>
  <ul>
    <li>
      <strong>created at: </strong><%= work_order.created_at.to_s(:default) %>
    </li>
    <li>
      <strong>state: </strong><%= work_order.aliquot_state %>
    </li>
    <li>
      <strong>barcode: </strong><%= work_order.aliquot.receptacle_barcode %>
    </li>
    <% work_order.details.to_h.each do |key, value|%>
      <li>
        <strong><%= "#{key}: "%> </strong><%= value %>
      </li>
    <% end %>
  </ul>

  <% work_order.lab_events.each do |lab_event|%>
    <h4><%= "#{lab_event.state.capitalize.humanize}: #{lab_event.name || lab_event.receptacle.barcode}"%></h4>
    <ul>
      <% unless lab_event.metadata.empty?%>
        <%lab_event.metadata.each do |key, value|%>
          <li>
            <strong><%= "#{key}: "%> </strong><%= value %>
          </li>
        <% end %>
        <br>
        <%= link_to "Edit #{lab_event.name} step", edit_pipeline_work_order_lab_event_path(pipeline, work_order, lab_event), { class: 'btn btn-primary btn-large', role: 'button' }%>
      <% end %>
    </ul>
  <% end %>
</section>