config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pipelines, param: :name, only: [:index] do
    resources :work_orders, only: %i[index show] do
      resources :lab_events
    end
    get 'reception', to: 'reception#index'
    post 'reception/upload', to: 'reception#upload'
    scope module: 'gridion' do
      resources :sequencing_runs
    end
  end

  resources :print_jobs, only: %i[create]

  match 'test_exception_notifier', controller: 'application',
                                   action: 'test_exception_notifier', via: :get

  # think about root
  root 'pipelines#index'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  attr_reader :pipeline
  before_action :set_pipeline

  # Ensure that the exception notifier is working. It will send an email to the standard email address.
  def test_exception_notifier
    raise 'This is a test. This is only a test.'
  end

  def set_pipeline
    @pipeline ||= Pipeline.find_by_name(params[:pipeline_name]) if params[:pipeline_name].present?
  end

  helper_method :pipeline
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper

  def current_year
    @current_year ||= Date.today.year
  end

  # returns link to the next lab_event
  # or link to sequencing_run if the next lab_event is 'sequencing'
  def link_to_next_lab_event_creation(pipeline, work_order)
    next_state = work_order.aliquot_next_state
    return new_pipeline_work_order_lab_event_path(pipeline, work_order,
      process_step_name: next_state) unless next_state =='sequencing'
    return pipeline_sequencing_runs_path(pipeline)
  end
end

app/views/application/_error_messages.html.erb
<% if target.errors.any? %>
  <div class="errors alert alert-danger">
    <h3><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h3>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_flashes.html.erb
<div class="flash">
  <% flash.each do |key, value| %>
    <div title="<%= key.to_s.humanize %>" class="<%= key %> alert alert-success">
      <p class="text-center"><%= value %></p>
    </div>
  <% end %>
</div>

app/views/application/_footer.html.erb
<footer class="footer">
  <p class="text-muted">&copy; Sanger Institute <%= current_year %></p>
</footer>

app/views/application/_header.html.erb
<header class="bg-inverse" >
    <div class="heading text-white" >
      <%= link_to 'TRACTION', root_path %>
    </div>
    <%= render 'nav' %>
</header>

app/views/application/_nav.html.erb
<nav>
  <div>
    <ul class="float-sm-right">
      <li><%= link_to "Reception", pipeline_reception_path(pipeline) %></li>
      <li><%= link_to "Work Orders", pipeline_work_orders_path(pipeline) %></li>
      <% pipeline.visible_process_steps.each do |process_step|%>
        <li><%= link_to process_step.name.humanize, pipeline_work_orders_path(pipeline, process_step_name: process_step.name) %></li>
      <% end %>
      <li><%= link_to "Sequencing Runs", pipeline_sequencing_runs_path(pipeline) %></li>
    </ul>
  </div>
</nav>

app/views/application/_print.html.erb
<div class="float-sm-right py-2">
  <%= label_tag :printer, 'Printer', class: 'h6' %>
  <%= select_tag(:printer_name, options_for_select(Printer.names)) %>
  <%= submit_tag "Print labels", class: "btn btn-primary pull-right ml-2", data: { disable_with: "Please wait..." }%>
</div>

app/views/application/_work_orders.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_tag print_jobs_path do %>
      <%= render "print" %>
      <table class="table table-striped">
        <thead>
          <th>Print Label</th>
          <th>Id</th>
          <th>Sample Name</th>
          <th>Action</th>
          <th>State</th>
          <th>Next Step</th>
          <th>&nbsp;</th>
        </thead>
        <tbody>
          <% work_orders.each do |work_order| %>
            <tr id="<%= dom_id(work_order) %>">
              <td><%= check_box_tag 'work_order_ids[]', work_order.id%></td>
              <td><%= work_order.id %></td>
              <td><%= work_order.name %></td>
              <td><%= work_order.action %></td>
              <td><%= work_order.aliquot_state %></td>
              <td>
                <%if work_order.aliquot_next_state.present?%>
                  <%= link_to work_order.aliquot_next_state, link_to_next_lab_event_creation(pipeline, work_order) %>
                <%end%>
              </td>
              <td><%= link_to 'Show', pipeline_work_order_path(pipeline, work_order) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>