config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pipelines, param: :name, only: [:index] do
    resources :work_orders, only: %i[index show] do
      resources :lab_events
    end
    get 'reception', to: 'reception#index'
    post 'reception/upload', to: 'reception#upload'
    scope module: 'gridion' do
      resources :sequencing_runs
    end
  end

  resources :print_jobs, only: %i[create]

  match 'test_exception_notifier', controller: 'application',
                                   action: 'test_exception_notifier', via: :get

  # think about root
  root 'pipelines#index'
end

app/controllers/reception_controller.rb
# frozen_string_literal: true

# reception for work orders from Sequencescape
class ReceptionController < ApplicationController
  def index
    @work_orders = Sequencescape::Api::WorkOrder.for_reception(pipeline)
  end

  # rubocop:disable Metrics/AbcSize
  def upload
    if params['work_orders_ids'].nil?
      redirect_to pipeline_reception_path(pipeline)
    else
      Sequencescape::Factory.create!(
        Sequencescape::Api::WorkOrder.find_by_ids(params['work_orders_ids']),
        pipeline
      )
      redirect_to pipeline_work_orders_path(pipeline),
                  notice: "#{params['work_orders_ids'].length}
                  Work orders were successfully uploaded"
    end
  end
  # rubocop:enable Metrics/AbcSize
end

app/controllers/receptions_controller.rb
# frozen_string_literal: true

# reception for work orders from sqsc
class ReceptionsController < ApplicationController
  def index
    @work_orders = Sqsc::Api::WorkOrder.for_reception
  end
end

app/views/reception/index.html.erb
<div class="title row">
  <div class="col-md-12">
    <h2>Work Orders  - Reception</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= form_tag pipeline_reception_upload_path(pipeline), method: :post do %>
      <table class="table table-striped">
        <thead>
          <th>&nbsp;</th>
          <th>Sample Name</th>
          <th>State</th>
        </thead>
        <tbody>
          <% @work_orders.each do |work_order| %>
            <tr id="<%= dom_id(work_order) %>">
              <td><%= check_box_tag 'work_orders_ids[]', work_order.id || "no_id" %></td>
              <td><%= work_order.name %></td>
              <td><%= work_order.state %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="form-group">
        <%= submit_tag "Upload", class: 'btn btn-primary pull-right',  data: { disable_with: "Please wait..." } %>
      </div>
    <% end %>
  </div>
</div>